title: 谢翔东
description: 机器学习研究员。研究方向包括多模态感知、稳定机器学习、与仿生神经网络。
theme: jekyll-theme-minimal
logo: /assets/img/headshot.jpg
show_downloads: false

markdown: kramdown
kramdown:
  input: GFM

plugins: []

github:
  is_project_page: false
